name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses:  Platane/snk/svg-only@main
        id: snake-gif
        with:
          github_user_name: yuanpngn
          outputs: dist/github-contribution-grid-snake.svg?palette=github-dark
          github_token: ${{ secrets.METRICS_TOKEN }}

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
